### PR TITLE
Ignore floats in mobiles

### PR DESCRIPTION
**Pull request by dy**
This should help with https://github.com/plotly/plotly.js/issues/280, at least for 3D part.
The only point is that touch interactions probably also should be fixed, that takes refactoring _mouse-change_ module.

### CODE REVIEW

**Comment by etpinard** [comment]
Looks good to me :dancer:

**Comment by etpinard** [comment]
@dfcreative in case you haven't noticed yet, grepping into http://cdn.plot.ly/plotly-latest.js reveals that [`gl-static-select`](https://github.com/gl-vis/gl-select-static) (which is a `gl-plot2d` dep) also uses `gl-fbo`.

**Comment by dy** [comment]
@etpinard thanks for the point.
_gl-select-static_ does not force `preferFloat` though, so it is always off and therefore does not cause issues in mobiles. In that regard that is a single point for plotly.

**Comment by dy** [comment]
Ok having [this](https://github.com/mikolalysenko/3d-view-controls/pull/1) merged enables simple mobile interactions.

**Pull request merged**
